apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-service
spec:
  selector:
    matchLabels:
      app: cat-service
  template:
    metadata:
      labels:
        app: cat-service
    spec:
      containers:
      - name: web
        image: us-central1-docker.pkg.dev/aipingxiao-louhi-test/my-app-repo/app:latest
        ports:
        - containerPort: 8080
